language: ruby

sudo: false

notifications:
  email:
    recipients:
      - "glen.robson@iiif.io"
    on_success: "change"
    on_failure: "change"

rvm:
- 2.4.2

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors

cache:
 - bundler
 - pip

install:
 - bundle install
 - pip install --upgrade pip
 - pip install --user awscli

script: ./scripts/test.sh

before_deploy: bundle exec jekyll clean && bundle exec jekyll build

deploy:
  - provider: s3
    access_key_id:
      secure: 3L/gJxiZA6XvSQzldRnZgMX8gYVpRegspyevoQeDKqrAMTNEDsIp+AOhcukwrZgDKZJgH8lNEhtcNqnHjukJkSa3ySWUq+Is3+RWYfQII0jgtYNMq5TEOo47B4unFo7lmIvG4uBjlDJxsInKec8DDgzFJjIog+ivvWjdXKkH/yc=
    secret_access_key:
      secure: nrH+05JoiR+XBSzmvnAoWyq/SO6zUeIYB/BMgpMENHO7Uyw5nVXOyFpituDyrqdgwqWgcjT7+X5JwgCVM3x01PCbaTbC5KzfMtlyneqn4btqONEoaQb7KF+QHrVzl/0F0acHqxOaCrJiAsnc61AjX3f0f7rwCQY6srTxvnfTwqY=
    bucket: showcase.iiif.io
    skip_cleanup: true
    acl: public_read
    region: us-east-1
    local_dir: _site
    on:
      branch: master
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
